/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import LinkedList.*;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        LinkedList<String> test = new LinkedList<String>();
        String trash = "Hello World";
        String trash2 = "GoodBye World";
        String trash3 = "Hello Again";

        test.add(trash);
        test.add(trash2);
        test.add(trash3);

        test.printList();
        try {
            System.out.println("Removido: "+test.remove(trash2));
        } catch (Exception ex) {
            System.out.println("Erro: "+ex.getMessage());
        }
        test.printList();

    }
}
